services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/custom-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - ADDONS_PATH=/odoo/odoo-src/odoo/addons,/mnt/custom-addons
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:
